import { Product } from './types';

export const neverWornProducts: Product[] = [
  {
    _id: 'lv-beanie-cream-black',
    name: 'Premium Cream & Black Two-Tone Beanie',
    slug: 'premium-cream-black-beanie',
    price: 85,
    image: '/lv-beanie-hero.png',
    description: 'Pristine never-worn designer beanie in cream and black two-tone. Features premium monogram pattern and comes with original dust bag and packaging. Authenticated and verified for authenticity.',
    stock: 1,
    size: 'One Size',
    color: 'Cream & Black',
    condition: 'never-worn',
    authenticated: true,
    featured: true,
    images: [
      '/lv-beanie-hero.png',
      '/lv-beanie-lifestyle-1.png',
      '/lv-beanie-lifestyle-2.png',
      '/lv-beanie-detail.png',
      '/lv-beanie-flatlay.png',
      '/seedance-9W0CqrpOoTpD7zpbIeLhj.png',
      '/seedance-bTMZYvAjLk34TbWqz6qv5.png',
      '/seedance-HN4MZRsuWTDX_ylZLNFuF.png',
      '/seedance-jnR4kJ3X08tCY9-Ms5wUH.png',
      '/seedance-xihRRL0EaBnV7jO8J7Mcl.png',
      '/product 1.png',
      '/product 2.png',
      '/WhatsApp Image 2026-05-08 at 12.33.49 AM.jpeg',
      '/WhatsApp Image 2026-05-08 at 12.33.49 AM (1).jpeg',
      '/WhatsApp Image 2026-05-08 at 12.33.50 AM.jpeg',
      '/WhatsApp Image 2026-05-08 at 12.33.50 AM (1).jpeg',
    ],
    details: {
      brand: 'Louis Vuitton',
      material: 'Premium Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
  {
    _id: 'luxury-black-beanie-1',
    name: 'Premium Luxury Black Designer Beanie',
    slug: 'luxury-black-designer-beanie',
    price: 75,
    image: '/placeholder-black-beanie.png',
    description: 'Never-worn premium black designer beanie. Crafted from high-quality materials with luxury branding. Pristine condition with original packaging.',
    stock: 1,
    size: 'One Size',
    color: 'Black',
    condition: 'never-worn',
    authenticated: true,
    featured: false,
    images: [
      '/placeholder-black-beanie.png',
      '/placeholder-black-beanie-2.png',
    ],
    details: {
      brand: 'Premium Designer',
      material: 'Luxury Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
  {
    _id: 'luxury-grey-beanie-1',
    name: 'Luxury Grey Designer Beanie',
    slug: 'luxury-grey-designer-beanie',
    price: 70,
    image: '/placeholder-grey-beanie.png',
    description: 'Never-worn premium grey designer beanie. Sophisticated styling perfect for luxury streetwear. Comes with original packaging and authentication.',
    stock: 1,
    size: 'One Size',
    color: 'Grey',
    condition: 'never-worn',
    authenticated: true,
    featured: false,
    images: [
      '/placeholder-grey-beanie.png',
      '/placeholder-grey-beanie-2.png',
    ],
    details: {
      brand: 'Premium Designer',
      material: 'Luxury Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
  {
    _id: 'luxury-burgundy-beanie-1',
    name: 'Luxury Burgundy Wine Beanie',
    slug: 'luxury-burgundy-wine-beanie',
    price: 78,
    image: '/placeholder-burgundy-beanie.png',
    description: 'Never-worn luxury burgundy wine-colored designer beanie. Premium quality with sophisticated aesthetic. Perfect condition with original packaging.',
    stock: 1,
    size: 'One Size',
    color: 'Burgundy',
    condition: 'never-worn',
    authenticated: true,
    featured: false,
    images: [
      '/placeholder-burgundy-beanie.png',
      '/placeholder-burgundy-beanie-2.png',
    ],
    details: {
      brand: 'Premium Designer',
      material: 'Luxury Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
  {
    _id: 'luxury-cream-beanie-1',
    name: 'Luxury Cream White Designer Beanie',
    slug: 'luxury-cream-white-beanie',
    price: 72,
    image: '/placeholder-cream-beanie.png',
    description: 'Never-worn luxury cream white designer beanie. Premium knit texture with elegant styling. Pristine condition, never worn or used.',
    stock: 1,
    size: 'One Size',
    color: 'Cream',
    condition: 'never-worn',
    authenticated: true,
    featured: false,
    images: [
      '/placeholder-cream-beanie.png',
      '/placeholder-cream-beanie-2.png',
    ],
    details: {
      brand: 'Premium Designer',
      material: 'Luxury Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
  {
    _id: 'luxury-navy-beanie-1',
    name: 'Luxury Navy Blue Designer Beanie',
    slug: 'luxury-navy-blue-beanie',
    price: 80,
    image: '/placeholder-navy-beanie.png',
    description: 'Never-worn luxury navy blue designer beanie. Professional styling for premium fashion. Comes with authentication and original packaging.',
    stock: 1,
    size: 'One Size',
    color: 'Navy',
    condition: 'never-worn',
    authenticated: true,
    featured: false,
    images: [
      '/placeholder-navy-beanie.png',
      '/placeholder-navy-beanie-2.png',
    ],
    details: {
      brand: 'Premium Designer',
      material: 'Luxury Knit',
      size: 'One Size Fits All',
      yearRelease: 2024,
      condition: 'Never Worn - Pristine',
      authentication: 'Verified Authentic',
    },
  },
];

export const getFeaturedProduct = () => {
  return neverWornProducts.find((p) => p.featured);
};

export const getProductBySlug = (slug: string) => {
  return neverWornProducts.find((p) => p.slug === slug);
};
